name: success
description: "Outil d'orientation SUCCESS ou comment choisir sa filière en 6 ETAPES"

publish_to: "none"

version: 1.0.0+5

environment:
  sdk: ">=3.2.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  page_transition: ^2.1.0
  easy_loading_button: ^0.3.2
  flutter_animation_progress_bar: ^2.3.1
  custom_keyboard: ^1.0.2
  flutter_chat_bubble: ^2.0.2
  animated_text_kit: ^4.2.2
  circular_bottom_navigation: ^2.4.0
  webview_flutter: ^4.5.0
  path_provider: ^2.1.3
  webview_flutter_android: ^3.16.1
  webview_flutter_wkwebview: ^3.10.2
  percent_indicator: ^4.2.3
  animator: ^3.3.0
  super_tooltip: ^2.0.7
  bounce: ^1.0.2
  awesome_dialog: ^3.2.1
  lottie: ^3.1.0
  sqflite: ^2.3.2
  adaptive_theme: ^3.6.0
  http: ^1.2.0
  youtube_player_flutter: ^9.0.1
  neon_widgets: ^2.0.0
  shared_preferences: ^2.2.3
  fluttertoast: ^8.2.6
  pin_code_text_field: ^1.8.0
  icons_launcher: ^2.1.7
  permission_handler: ^10.2.0
  confetti: ^0.6.0
  flutter_phone_direct_caller: ^2.1.1

  path: any
icons_launcher:
  image_path: "assets/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
    - assets/images/home_screen/
    - assets/lotties/
    - shorebird.yaml

  fonts:
    - family: DINNextRoundedLTProMedium
      fonts:
        - asset: assets/fonts/DINNextRoundedLTPro-Medium.ttf
